### ISSUE TITLE
Adding conda environment within container

### ISSUE THREAD

**Issue by ggabernet** [grst/rstudio-server-conda#24]
Hi @grst ,

thanks for the very useful repository!

I was just wondering if it would be possible to run the rstudio server within a docker container, providing the conda environment with all the dependencies within that container as well, so it can be ported to different instances and the analysis reproduced easily.

I've tried like this:

Dockerfile:
```
FROM rocker/rstudio

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV CONDA_DIR /home/rstudio/conda

RUN apt-get update --fix-missing \
  && apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion \
  && apt-get clean

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /home/rstudio/miniconda.sh \
    && bash /home/rstudio/miniconda.sh -b -p /home/rstudio/conda \
    && rm -f /home/rstudio/miniconda.sh

ENV PATH=$CONDA_DIR/bin:$PATH
RUN which conda
RUN conda --version

COPY environment.yml /
RUN conda env create -f /environment.yml && conda clean -a -y

RUN conda env list
ENV PATH=$CONDA_DIR/envs/<envname>/bin:$PATH

ADD init2.sh /init2.sh

CMD ["/init2.sh"]
```

And docker-compose.yml:
```
version: "3.5"
services:
  rstudio:
    build: .
    # add the image name of your container
    image: <image-tag>
    ulimits:
      nofile: 10000
    ports:
        - "8889:8787"
    volumes:
      # mount the working directory containing your R project.
      - /mnt/volume/qsvac:/home/rstudio
      # share settings between rstudio instances
      - /home/centos/.local/share/rstudio/monitored/user-settings:/home/rstudio/.local/share/rstudio/monitored/user-settings
      # mount tempdir
      - /mnt/volume/rstudio-tmp/var/lib:/var/lib/rstudio-server
      - /mnt/volume/rstudio-tmp/var/run:/var/run/rstudio-server
      - /mnt/volume/rstudio-tmp/tmp:/tmp
    environment:
      - PASSWORD=notsafe
      # repeat the path of the conda environment
      - CONDAENV=/home/rstudio/conda/envs/<conda-env>
```

Also tested without sharing the rstudio settings and without mounting any tempdirs here. Unfortunately with no luck. If you happen to have an example on how to do that, that would be very helpful!
